version: '3'

services:
  proxy:
    container_name: proxy_container
    hostname: proxy
    build:
      context: proxy
    image: mynginx_pr
    ports:
      - 8080:80
    environment:
      - TYPE=proxy
  service_a:
    container_name: serv_a_container
    image: mynginx_sv_a
    build:
      context: service_a
    networks:
      default:
        aliases:
          - service_a
    environment:
      - TYPE=service_a
  service_b:
    container_name: serv_b_container
    image: mynginx_sv_b
    build:
      context: service_b
    networks:
      default:
        aliases:
          - service_b
    environment:
      - TYPE=service_b
networks:
  default:
    name: proxy-dev
    external: true
